# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Watchanan Chantapakul
title_thai: วัชนันท์ จันทาภากุล
email: tmwatchanan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love technologies especially about computer things, thus, this website was created with my enthusiasm for the web development technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tmwatchanan.github.io" # the base hostname & protocol for your site
github_username: tmwatchanan
linkedin_username: watchanan
twitter_username: WatchananC

# Build settings
markdown: kramdown

plugins_dir:
  - jekyll-seo-tag
