
# Site settings
title: Watchanan Chantapakul GitHub Pages
email: tmwatchanan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Watchanan Chantapakul graduated with Bachelor's degree in Computer Engineering from Chaing Mai University.
  He is interested many topics, for example, machine learning, artificial intelligence, and computer vision.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://tmwatchanan.github.io" # the base hostname & protocol for your site
twitter:
  username: watchananc
  card: summary
social:
  name: Watchanan Chantapakul
  links:
    - https://www.linkedin.com/in/watchanan/
    - https://github.com/tmwatchanan/
    - https://twitter.com/watchananc
    - https://medium.com/@watchanan
    - https://keybase.io/watchanan
plugins:
  - jekyll-seo-tag
